/*
 *  QLiteOSD is an simple OSD for DJI FPV System:
 *  This is an Arduino project that handles basic OSD functions
 *  from BMP280 to a Simple Voltage Sensor to feed it 
 *  to DJI FPV System.
 *
 * ------------------------------------------------
 *
 * Copyright (C) 2023 David Payne
 * 
 * This software is based on and uses software published by Paul Kurucz (pkuruz):opentelem_to_bst_bridge
 * as well as software d3ngit : djihdfpv_mavlink_to_msp_V2 and crashsalot : VOT_to_DJIFPV
 * 
 * License info: See the LICENSE file at the repo top level
 *
 * THIS SOFTWARE IS PROVIDED IN AN "AS IS" CONDITION. NO WARRANTIES,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING, BUT NOT LIMITED
 * TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
 * PARTICULAR PURPOSE APPLY TO THIS SOFTWARE. THE COMPANY SHALL NOT,
 * IN ANY CIRCUMSTANCES, BE LIABLE FOR SPECIAL, INCIDENTAL OR
 * CONSEQUENTIAL DAMAGES, FOR ANY REASON WHATSOEVER.
 *
 */


static const char HEAD_TITLE[] PROGMEM = "<!DOCTYPE html><html lang='en'><head><meta charset='UTF-8'>"
                                        "<meta http-equiv='Content-Type' content='text/html; charset=UTF-8' />"
                                        "<link rel='icon' href='data:;base64,='>"
                                        "<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
                                        "<title>QLiteOSD</title>"
                                        "	<style>"
                                        "        body {"
                                        "            font-family: Arial, sans-serif;"
                                        "            margin: 0;"
                                        "            padding: 0;"
                                        "        }"
                                        "        header {"
                                        "            background-color: #4CAF50;"
                                        "            color: white;"
                                        "            padding: 1em 0;"
                                        "            text-align: center;"
                                        "        }"
                                        "        nav {"
                                        "            background-color: #333;"
                                        "            display: flex;"
                                        "            justify-content: space-between;"
                                        "            align-items: left, top;"
                                        "            padding: 0 16px;"
                                        "        }"
                                        "        nav ul {"
                                        "            list-style-type: none;"
                                        "            margin: 0;"
                                        "            padding: 0;"
                                        "            overflow: hidden;"
                                        "            display: flex;"
                                        "            flex-direction: row;"
                                        "        }"
                                        "        nav ul li {"
                                        "            display: inline;"
                                        "        }"
                                        "        nav ul li a {"
                                        "            display: block;"
                                        "            color: white;"
                                        "            text-align: left;"
                                        "            padding: 14px 16px;"
                                        "            text-decoration: none;"
                                        "        }"
                                        "        nav ul li a:hover {"
                                        "            background-color: #111;"
                                        "        }"
                                        "        .menu-icon {"
                                        "            display: none;"
                                        "            padding: 14px 16px;"
                                        "            cursor: pointer;"
                                        "        }"
                                        "        .menu-icon span {"
                                        "            display: block;"
                                        "            width: 25px;"
                                        "            height: 3px;"
                                        "            margin: 5px auto;"
                                        "            background-color: white;"
                                        "        }"
                                        "        @media (max-width: 600px) {"
                                        "            nav ul {"
                                        "                display: none;"
                                        "                flex-direction: column;"
                                        "                width: 100%;"
                                        "            }"
                                        "            nav ul li {"
                                        "                float: none;"
                                        "                width: 100%;"
                                        "            }"
                                        "            .menu-icon {"
                                        "                display: block;"
                                        "            }"
                                        "        }"
                                        "        .show {"
                                        "            display: flex !important;"
                                        "        }"
                                        "        section {"
                                        "            padding: 20px;"
                                        "        }"
                                        "        form button {"
                                        "            width: 100%;"
                                        "            background-color: #4CAF50;"
                                        "            color: white;"
                                        "            padding: 14px 20px;"
                                        "            margin: 10px 0;"
                                        "            border: none;"
                                        "            border-radius: 8px;"
                                        "            cursor: pointer;"
                                        "        }"
                                        "        form button:hover {"
                                        "            background-color: #45a049;"
                                        "        }"
                                        "        .group {"
                                        "            margin-bottom: 20px;"
                                        "        }"
                                        "        table { width: 100%; border-collapse: collapse; margin-top: 20px; }"
                                        "        .item { margin-left: 20px; display: flex; align-items: center; }"
                                        "        .readonly-field { margin-left: 10px; display: block; width: 75px; }"
                                        "        th, td { border: 1px solid #000; text-align: center; padding: 5px; cursor: pointer; }"
                                        "        th { background-color: #f2f2f2; }"
                                        "        .selected-cell { background-color: #FFD700; /* Gold background for selected cells */ }"
                                        "        .selected-item { background-color: #90EE90; /* Light Green background for selected items */ }"
                                        "    </style>";

static const char BODY_MENU[] PROGMEM = "</head><body>"
                                        "    <header>"
                                        "        <h1>QLiteOSD</h1>"
                                        "    </header>"
                                        "    <nav>"
                                        "        <div class='menu-icon' onclick='toggleMenu()'>"
                                        "            <span></span>"
                                        "            <span></span>"
                                        "            <span></span>"
                                        "        </div>"
                                        "        <ul id='menu'>"
                                        "            <li><a href='/'>Home</a></li>"
                                        "            <li><a href='/configure'>Configure</a></li>"
                                        "            <li><a href='/osd'>OSD Layout</a></li>"
                                        "            <li><a href='/wifioff' onclick='return confirm(\"Do you want to turn off Wifi Access Point and start OSD again?\")'>Turn Off Wifi</a></li>"
                                        "            <li><a href='/reset' onclick='return confirm(\"Do you want to delete all logs and reset to default settings?\")'>Reset</a></li>"
                                        "        </ul>"
                                        "    </nav>"
                                        "<section><p>";
                                      
static const char BODY_END[] PROGMEM = "<br/><br/><br/><hr/>QLiteOSD v%VERSION%</p></section>"
                                          "    <script>"
                                          "        function toggleMenu() {"
                                          "            var menu = document.getElementById('menu');"
                                          "            if (menu.classList.contains('show')) {"
                                          "                menu.classList.remove('show');"
                                          "            } else {"
                                          "                menu.classList.add('show');"
                                          "            }"
                                          "        }"
                                          "    </script>"
                                          "</body></html>";

static const char CONFIG_FORM[] PROGMEM = "<h2>Configuration:</h2><form action='/saveconfig' method='get'>"
                          "<p><label>Craft Name</label><input type='text' name='craftname_form' value='%CRAFTNAME%' maxlength='14'></p>"
                          "<p><input name='use_imperial_form' type='checkbox' %USEIMPERIALCHECKED%> Use Imperial Units</p>"
                          "<p><input name='use_pwm_arm_form' type='checkbox' %USEPWMCHECKED%> Arm with PWM Switch (D5 pin)</p>"
                          "<button type='submit'>Save</button></form>";      

static const char OSD_JS[] PROGMEM =    "<script>function handleCellClick(e){let t=document.querySelector('input[name=\"item\"]:checked');"
                                        "if(t){let l=t.getAttribute('data-item-number'),r=t.id,a=e.target.getAttribute('data-value');if(11>=e.target.textContent.trim()){alert('This cell is already occupied. Please choose another cell.');"
                                        "return}let n=document.querySelectorAll('.readonly-field');for(let o of n)if(o.value===a&&234!=a){alert('This value is already assigned to another OSD item. Please choose another cell.');"
                                        "return}let i=document.querySelectorAll('td');for(let c of i)if(c.innerText===l){c.style.backgroundColor='#FFFFFF',c.innerText=c.getAttribute('data-value');"
                                        "break}234!=e.target.textContent&&(e.target.textContent=l,e.target.classList.add('selected-cell'),e.target.style.backgroundColor=getColorByNumber(l));"
                                        "let d=document.getElementById(r+'Field');d.value=a,d.style.backgroundColor='',234!=e.target.textContent&&(d.style.backgroundColor=getColorByNumber(l))}else alert('Please select an OSD item first.')}function getColorByNumber(e){let t=['#FFB6C1','#87CEFA','#98FB98','#FFD700','#DDA0DD','#FF6347','#40E0D0','#FFA07A','#EE82EE','#F5DEB3','#B2D7D5'];"
                                        "return t[(e-1)%t.length]}function handleRadioChange(e){let t=document.querySelectorAll('.item');t.forEach(e=>{e.classList.remove('selected-item')});"
                                        "let l=e.target.parentElement;l.classList.add('selected-item')}function init(){let e=document.querySelectorAll('td');"
                                        "e.forEach(e=>{e.addEventListener('click',handleCellClick)});let t=document.querySelectorAll('input[name=\"item\"]');t.forEach(e=>{e.addEventListener('change',handleRadioChange)})}window.onload=init;</script>";
                          
static const char OSD_DISPLAY[] PROGMEM = "    <h1>OSD Layout</h1>"
                                  "    <div class='group'>"
                                  "        <h2>Select an OSD Item</h2><form action='/saveosd' method='get'>"
                                  "        <div class='item'>"
                                  "            <input type='radio' id='item1' name='item' value='altitude' data-item-number='1'>"
                                  "            <label for='item1'>1. Altitude</label>"
                                  "            <input name='altitude_pos' value='%ALT_VAL%' type='text' id='item1Field' class='readonly-field' readonly>"
                                  "        </div>"
                                  "        <div class='item'>"
                                  "            <input type='radio' id='item2' name='item' value='cellVoltage' data-item-number='2'>"
                                  "            <label for='item2'>2. Cell Voltage</label>"
                                  "            <input name='cell_voltage_pos' value='%CELL_VAL%' type='text' id='item2Field' class='readonly-field' readonly>"
                                  "        </div>"
                                  "        <div class='item'>"
                                  "            <input type='radio' id='item3' name='item' value='batteryVoltage' data-item-number='3'>"
                                  "            <label for='item3'>3. Battery Voltage</label>"
                                  "            <input name='main_batt_voltage_pos' value='%BAT_VAL%' type='text' id='item3Field' class='readonly-field' readonly>"
                                  "        </div>"
                                  "        <div class='item'>"
                                  "            <input type='radio' id='item4' name='item' value='craftName' data-item-number='4'>"
                                  "            <label for='item4'>4. Craft Name</label>"
                                  "            <input name='craft_name_pos' value='%CRAFT_VAL%' type='text' id='item4Field' class='readonly-field' readonly>"
                                  "        </div>"
                                  "        <div class='item'>"
                                  "            <input type='radio' id='item5' name='item' value='satellites' data-item-number='5'>"
                                  "            <label for='item5'>5. Satellites</label>"
                                  "            <input name='gps_sats_pos' value='%SATS_VAL%' type='text' id='item5Field' class='readonly-field' readonly>"
                                  "        </div>"
                                  "        <div class='item'>"
                                  "            <input type='radio' id='item6' name='item' value='homeArrow' data-item-number='6'>"
                                  "            <label for='item6'>6. Home Arrow</label>"
                                  "            <input name='home_dir_pos' value='%HOMEARROW_VAL%' type='text' id='item6Field' class='readonly-field' readonly>"
                                  "        </div>"
                                  "        <div class='item'>"
                                  "            <input type='radio' id='item7' name='item' value='distanceFromHome' data-item-number='7'>"
                                  "            <label for='item7'>7. Distance from Home</label>"
                                  "            <input name='home_dist_pos' value='%DIST_VAL%' type='text' id='item7Field' class='readonly-field' readonly>"
                                  "        </div>"
                                  "        <div class='item'>"
                                  "            <input type='radio' id='item8' name='item' value='groundSpeed' data-item-number='8'>"
                                  "            <label for='item8'>8. Ground Speed</label>"
                                  "            <input name='gps_speed_pos' value='%SPEED_VAL%' type='text' id='item8Field' class='readonly-field' readonly>"
                                  "        </div>"
                                  "        <div class='item'>"
                                  "            <input type='radio' id='item9' name='item' value='latitude' data-item-number='9'>"
                                  "            <label for='item9'>9. Latitude</label>"
                                  "            <input name='gps_lat_pos' value='%LAT_VAL%' type='text' id='item9Field' class='readonly-field' readonly>"
                                  "        </div>"
                                  "        <div class='item'>"
                                  "            <input type='radio' id='item10' name='item' value='longitude' data-item-number='10'>"
                                  "            <label for='item10'>10. Longitude</label>"
                                  "            <input name='gps_lon_pos' value='%LON_VAL%' type='text' id='item10Field' class='readonly-field' readonly>"
                                  "        </div>"
                                  "        <div class='item'>"
                                  "            <input type='radio' id='item11' name='item' value='longitude' data-item-number='11'>"
                                  "            <label for='item11'>11. Crosshair</label>"
                                  "            <input name='crosshairs_pos' value='%CROSS_VAL%' type='text' id='item11Field' class='readonly-field' readonly>"
                                  "        </div>"
                                  "		<button type='submit'>Save OSD Selections</button>"
                                  "		</form>"
                                  "    </div>"
                                  "    <h2>Select Item Location</h2>"
                                  "	<table>"
                                  "		<tbody>"
                                  "			<td data-value='234'>234</td>"
                                  "		</tbody>"
                                  "	<table>"
                                  "	* 234 will hide the OSD element."
                                  "	<table>"
                                  "        <tbody>"
                                  "            <script>"
                                  "                let start = 2048;"
                                  "                let increment = 1;"
                                  "                let additionalIncrement = 5;"
                                  "                let currentNumber = start;"
                                  "				let displayNumber = currentNumber;"
                                  "				let itemCount = 1;"
                                  "				const readOnlyFields = document.querySelectorAll('.readonly-field');"
                                  "                for (let i = 0; i < 16; i++) {"
                                  "                    document.write('<tr>');"
                                  "                    for (let j = 0; j < 27; j++) {"
                                  "						displayNumber = currentNumber;"
                                  "						for (let field of readOnlyFields) {"
                                  "							if (field.value == currentNumber) {"
                                  "								displayNumber = itemCount;"
                                  "								break;"
                                  "							}"
                                  "							itemCount++;"
                                  "						}"
                                  "						itemCount = 1;"
                                  "                        document.write('<td data-value=\' + currentNumber +  \'>' + displayNumber + '</td>');"
                                  "                        currentNumber += increment;"
                                  "                    }"
                                  "                    currentNumber += additionalIncrement;"
                                  "                    document.write('</tr>');"
                                  "                }"
                                  "				const tableCells = document.querySelectorAll('td');"
                                  "				let cellValue = 0;"
                                  "				for (let cellX of tableCells) {"
                                  "					cellValue = cellX.innerText;"
                                  "					if (cellValue <= 11) {"
                                  "						cellX.style.backgroundColor = getColorByNumber(cellValue);"
                                  "						readOnlyFields[(cellValue-1)].style.backgroundColor = cellX.style.backgroundColor;"
                                  "					}"
                                  "				}"
                                  "            </script>"
                                  "        </tbody>"
                                  "    </table>";

